### ISSUE TITLE
migrate to null-safety

### ISSUE THREAD

**Issue by ghost** [prasso/prasso_app#8]
Hi guys,

Hope you are all well !

I wanted to give a try to your prasso app but was wondering if you can migrate it to null safety first.

Thanks for any insights or inputs on that

Cheers,
Luc

**Comment by bperreault** [comment]
Hi, @lucmichalski 
We have that on our plan and will be working to do so as soon as Optamize.app is out the door.
Thank you for your contribution, if you would like to assist with a PR it would be greatly appreciated.

**Comment by bperreault** [comment]
Working on this
